name: Docker Image CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  # Change this to your docker hub username and image name
  IMAGE_NAME: chungchungyon/bike_tracker

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      # Only run this step if it's a push to main/master, not a PR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build_and_push
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    steps:
    - name: Deploy to self-hosted runner
      run: |
        docker pull ${{ env.IMAGE_NAME }}:latest
        docker stop bike_tracker || true
        docker rm bike_tracker || true
        docker run -d --restart unless-stopped --name bike_tracker -p 8000:8000 -v "C:\Users\apf_temp_admin\Documents\strava_activity\export_55559181:/app/data" -e STRAVA_DATA_DIR=/app/data ${{ env.IMAGE_NAME }}:latest
